### ISSUE TITLE
Support CamelCase Component Names

### ISSUE THREAD

**Issue by jermspeaks** [jermspeaks/generator-react-redux#8]
When writing the argument for component name in the sub-generator, `component`, please allow no change in the CamelCase formatting.
### Tasks:
- [x] Folder name use CamelCase
- [x] File names use CamelCase
- [x] class name use CamelCase
- [x] import styles name use CamelCase
- [x] Filename in `package.json` use camelcase

**Comment by jermspeaks** [comment]
Closed with [release v1.1.5](https://github.com/jermspeaks/generator-react-redux/releases/tag/v1.1.5).
